# SQLite version 3.x

default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: dcmpls_development

test:
  <<: *default
  database: dcmpls_test

production:
  <<: *default
  database: dcmpls_production
